"""Add password reset tokens table

Revision ID: 0edbd362e651
Revises: 4e6a8322f465
Create Date: 2025-11-03 00:04:22.770942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edbd362e651'
down_revision = '4e6a8322f465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_password_reset_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_password_reset_is_used', ['is_used'], unique=False)
        batch_op.create_index('idx_password_reset_token_hash', ['token_hash'], unique=False)
        batch_op.create_index('idx_password_reset_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_password_reset_user_created')
        batch_op.drop_index('idx_password_reset_token_hash')
        batch_op.drop_index('idx_password_reset_is_used')
        batch_op.drop_index('idx_password_reset_expires_at')

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
