"""Add ResumeFile table for file management

Revision ID: 4e6a8322f465
Revises: e5218d5636ae
Create Date: 2025-11-01 17:45:53.733758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6a8322f465'
down_revision = 'e5218d5636ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('s3_bucket', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("processing_status in ('pending', 'processing', 'completed', 'failed')", name='check_valid_processing_status'),
    sa.CheckConstraint("storage_type in ('local', 's3')", name='check_valid_storage_type'),
    sa.CheckConstraint('file_size > 0', name='check_positive_file_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.create_index('idx_active_files', ['is_active'], unique=False)
        batch_op.create_index('idx_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('idx_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.drop_index('idx_user_created')
        batch_op.drop_index('idx_processing_status')
        batch_op.drop_index('idx_active_files')

    op.drop_table('resume_files')
    # ### end Alembic commands ###
